### ISSUE TITLE
Integrate keystone-storage-adapter-s3

### ISSUE THREAD

**Issue by radiovisual** [keystonejs/keystone-test-project#16]
> Per the conversation with @JedWatson on Slack (#dev):

To get the new [keystonejs/keystone-storage-adapter-s3](https://github.com/keystonejs/keystone-storage-adapter-s3) that @josephg contributed integrated into keystone-test-project:
### Steps are [basically]:

**In keystone-test-project:**
- [x] add the `keystone-storage-adapter-s3` dependency using the git url to the test project’s `package.json`
- [x] if (and only if) S3 environment variables are present, create an adapter in the `Files` list and add a field that uses it
- [x] load the Admin UI, make sure the new field works as expected (upload / remove files, check they exist in S3 with the correct headers, etc)

**In keystonejs/keystone:**
- [x] edit `admin/client/utils/List.js` and remove both instances of `/legacy` (this will switch you over to the new api)

I can take this task on if nobody else is working on it...

**Comment by radiovisual** [comment]
3 out of 4 tasks above are complete in PR #18 , now I just need to get far enough to run keystone without runtime errors to test the Admin UI. I will sniff around the code some more to see if I can figure out where the bugs are coming from

**Comment by josephg** [comment]
Awesome. Let me know if you run into any problems with the S3 adapter. Now's the time to fix issues that come up!

**Comment by JedWatson** [comment]
This is all working now 😀

**Comment by radiovisual** [comment]
Nice! 🍔  🎉  😄  !!!
